### ISSUE TITLE
Mac Book Pro not working anymore

### ISSUE THREAD

**Issue by NilsEckelt** [yamartino/pressure#26]
It looks like Apple updated Safari or something happened and the library is not working anymore.
Website says, 'NOT supported' if clicked on test button in Safari.

**Comment by yamartino** [comment]
@NilsEckelt what version of safari are you running?

**Comment by yamartino** [comment]
@NilsEckelt I am running the most recent version of Safari v9.0.3 and it seems to be working for me. Check out this issue #5 and see if any of that information helps you troubleshoot. Keep me posted! :smile:

**Comment by yamartino** [comment]
@NilsEckelt first thing to try is restarting safari

**Comment by NilsEckelt** [comment]
Okay. It is working now. I just had to restart my MacBook. Who had thought of that. Thanks.

**Comment by yamartino** [comment]
@NilsEckelt glad to see you were able to fix it. It is such a bummer that Safari is so buggy on Mac :cry:
