### ISSUE TITLE
Status of Force Touch in Chrome?

### ISSUE THREAD

**Issue by albinekb** [yamartino/pressure#6]
Hello, do you have any idea on if/when chrome will support force touch on os x?

**Comment by yamartino** [comment]
@albinekb it looks like there is a feature request for Chrome to add Force Touch feature support on OSX: https://code.google.com/p/chromium/issues/detail?id=481890

However, that is only to add things like force touching a word to look it up in the dictionary, I have seen no word on Chrome adding support for web interactions yet. Hopefully there will eventually be support, and when/if they do, pressure will be the first to add it ;)

**Comment by albinekb** [comment]
@yamartino yeah it's sad they haven't added it yet, and it looks like they're not planning to (?) 
So much awesome stuff could be built!
